#Custom config options
#Wed Nov 30 19:22:39 MSK 2016
hideTressp=false
sfx_vol=18
GoogleAPIKey=API-KEY
onlineNotifier=true
alert_vol=20
objectBlink=false
show_minimap_profits=true
new_minimap=true
hideBatt=false
flaskMeters=true
sshot_noui=false
use_smileys=false
hideMurd=false
hcolor=0,0,226,129
sound_on=true
timestamp=false
showDayTime=true
pathfinder=true
showBeast=true
showOtherNames=true
toggleCL=false
showq=true
pathfinderLine=false
sshot_nonames=false
flaskNum=100
hideTheft=false
toggleCA=true
hideObjects=gfx/tiles/dwald,gfx/arch/cabin,gfx/terobjs/bumlings,gfx/arch/gates,gfx/terobjs/trees,gfx/arch/inn,gfx/tiles/wald,gfx/terobjs/plants,gfx/terobjs/ridges/mountain/,gfx/terobjs/blood,
showRadius=true
simple_plants=true
show_direction=true
hideVand=false
showNames=true
sshot_compress=false
hideAsslt=false
soundMemo=false
show_gob_health=true
flaskFillOnly=false
toggleTR=true
music_on=false
pathfinderRectangles=false
showpath=true
customNeg=true
show_minimap_players=true
showpathAll=true
noborders=false
show_minimap_radius=true
zoom=true
newclaim=false
tileAA=true
autoSaveMinimaps=false
objMouseHLight=false
drawIcons=false
showHidden=true
showFlavors=false
music_vol=0
new_chat=false
