#Window config options
#Wed Nov 30 19:22:09 MSK 2016
minimap_pos=(2, 679)
toolbar2_folded=true
study_locked=true
toolbar3_folded=true
menugrid_sz=(154, 152)
toolbar1_pos=(4, 170)
toolbar2_locked=false
toolbar3_locked=false
menugrid_pos=(1229, 866)
Study_pos=(1383, 818)
toolbar3_pos=(54, 171)
toolbar1_folded=false
Character\ Sheet_pos=(1049, 401)
Equipment_pos=(1495, 534)
minimap_sz=(389, 291)
Kin_pos=(252, 146)
Cupboard_pos=(357, 86)
toolbar1_locked=true
toolbar2_pos=(294, 11)
Inventory_pos=(403, 757)
